name: home_renting
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  flutter_slidable: ^2.0.0
  font_awesome_flutter: ^10.3.0
  flutter_screenutil: ^5.7.0

  #share socials
  flutter_share_me: ^1.4.0

  # Images
  image_picker: ^0.8.6
  cached_network_image: ^3.2.3

  # State management
  stacked: ^3.0.1
  stacked_services: ^0.9.8
  
  # Firebase services
  firebase_core: ^2.3.0
  cloud_firestore: ^4.3.0
  firebase_auth: ^4.2.3
  firebase_storage: ^11.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  stacked_generator: ^0.8.1
  build_runner: ^2.3.3
  flutter_launcher_icons: ^0.11.0

# flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/fucci_logo.png"

flutter:

  uses-material-design: true

  
  assets:
    - assets/images/
 
