name: home_renting
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_slidable: ^2.0.0
  font_awesome_flutter: ^10.3.0
  flutter_screenutil: ^5.7.0
  lottie: ^2.3.0
  cool_stepper: ^1.2.1
  google_fonts: ^4.0.4
  http:
  path_provider:
  share_plus: ^7.0.2


  #share socials
  flutter_share_me: ^1.4.0

  # Images
  image_picker: any
  cached_network_image: any

  # State management
  stacked: ^3.4.0
  stacked_services: ^1.1.0 
  
  # Firebase services
  firebase_core: ^2.13.0
  cloud_firestore: ^4.7.1
  firebase_auth: ^4.6.1
  firebase_storage: ^11.2.1
  shared_preferences: ^2.0.20

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  stacked_generator: ^1.3.3
  build_runner: ^2.4.4
  flutter_launcher_icons: ^0.11.0

# flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/fucci_logo.png"

flutter:

  uses-material-design: true

  
  assets:
    - assets/images/
    - assets/json/
 
