import 'package:home_renting/core/models/property.dart';

class HomeService {
  List<Property> getHomes() {
    final homes = [
      Property(
        description: "",
        id: "1",
       imageUrl: "assets/images/house3.jpg",
          imageFilename: "",
        name: "Cubana Villa",
        type: "Duplex",
        location: "Lagos",
        owner: "Darlignton Onwukwe",
        isAvalable: "yes",
        address: "3,Ife Street",
        price: "1,500,000",
        numberOfBathroom: "4",
        numberOfBedrooms: "3",
      ),
      Property(
        description: "",
        id: "2",
      imageUrl: "assets/images/house3.jpg",
          imageFilename: "",
        name: "Ayo nio House",
        type: "Self Contain",
        location: "Lagos",
        owner: "Darlignton Onwukwe",
        isAvalable: "yes",
        address: "9, Tango Street Lagos",
        price: "400,000",
        numberOfBathroom: '2',
        numberOfBedrooms: "1",
      ),
      Property(
          description: "",
          id: "3",
          imageUrl: "assets/images/house3.jpg",
          imageFilename: "",
          name: "Dundee Street 5",
          type: "Self Contain",
          location: "Abuja",
          owner: "Utunu",
          isAvalable: "no",
          address: "block 3, Street 5, Dundee Estate",
          price: "200,000",
          numberOfBathroom: "2",
          numberOfBedrooms: "1"),
      Property(
        description: "",
        id: "4",
       imageUrl: "assets/images/house3.jpg",
        imageFilename: "",
        name: "Atamah Compound",
        type: "A room and palour self contain",
        location: "PH",
        owner: "Utunu",
        isAvalable: "no",
        address: "6,Dickson Street, RumuIgbo",
        price: "600,000",
        numberOfBathroom: "3",
        numberOfBedrooms: "2",
      ),
      Property(
        id: "5",
       imageUrl: "assets/images/house3.jpg",
          imageFilename: "",
        name: "Alhaja lasisi house",
        type: "A room and palour self contain",
        location: "Ibadan",
        owner: "teg",
        isAvalable: 'yes',
        address: "15, Dickson Street, Bodijah, Ibandan",
        price: "500,000",
        numberOfBathroom: "2",
        numberOfBedrooms: "1",
        description: "",
      ),
    ];

    return homes;
  }
}
